apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: weka-nri-cpuset
  namespace: kube-system
  labels:
    app: weka-nri-cpuset
spec:
  updateStrategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: "100%"
  selector:
    matchLabels:
      app: weka-nri-cpuset
  template:
    metadata:
      labels:
        app: weka-nri-cpuset
    spec:
      serviceAccountName: weka-nri-cpuset
      restartPolicy: Always
      hostNetwork: true
      hostPID: true
      securityContext:
        runAsUser: 0
      containers:
      - name: weka-cpuset
        image: PLACEHOLDER_IMAGE_TAG
        imagePullPolicy: IfNotPresent
        args:
        - "--socket=/var/run/nri/nri.sock"
        - "--log-level=info"
        securityContext:
          privileged: true
        env:
        - name: NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        volumeMounts:
        - name: nri-socket
          mountPath: /var/run/nri
        - name: sys-fs
          mountPath: /sys
          readOnly: true
        - name: proc
          mountPath: /proc
          readOnly: true
        resources:
          requests:
            memory: "64Mi"
            cpu: "100m"
          limits:
            memory: "128Mi"
            cpu: "500m"
        livenessProbe:
          exec:
            command:
            - /usr/local/bin/weka-cpuset
            - --version
          initialDelaySeconds: 30
          periodSeconds: 60
        readinessProbe:
          exec:
            command:
            - /usr/local/bin/weka-cpuset  
            - --version
          initialDelaySeconds: 5
          periodSeconds: 10
      volumes:
      - name: nri-socket
        hostPath:
          path: /var/run/nri
          type: DirectoryOrCreate
      - name: sys-fs
        hostPath:
          path: /sys
          type: Directory
      - name: proc
        hostPath:
          path: /proc
          type: Directory
      tolerations:
      - operator: Exists
        effect: NoSchedule
      - operator: Exists
        effect: NoExecute
      nodeSelector:
        kubernetes.io/os: linux
