kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
# Use Kubernetes v1.32.5
name: test
containerdConfigPatches:
- |-
  [plugins."io.containerd.grpc.v1.nri"]
    enable = true
    plugin_path = ["/opt/nri/plugins"]
    socket_path = "/run/containerd/nri/nri.sock"
    plugin_registration_timeout = "15s"
nodes:
- role: control-plane
  image: kindest/node:v1.32.5
  extraMounts:
  - hostPath: /tmp/nri-plugins
    containerPath: /opt/nri/plugins
  - hostPath: /tmp/nri-run
    containerPath: /run/containerd/nri
  kubeadmConfigPatches:
  - |
    kind: InitConfiguration
    nodeRegistration:
      kubeletExtraArgs:
        cpu-manager-policy: static
        system-reserved: cpu=500m,memory=1Gi
        kube-reserved: cpu=500m,memory=1Gi
- role: worker
  image: kindest/node:v1.32.5
  extraMounts:
  - hostPath: /tmp/nri-plugins
    containerPath: /opt/nri/plugins
  - hostPath: /tmp/nri-run
    containerPath: /run/containerd/nri
  kubeadmConfigPatches:
  - |
    kind: JoinConfiguration
    nodeRegistration:
      kubeletExtraArgs:
        cpu-manager-policy: static
        system-reserved: cpu=500m,memory=1Gi
        kube-reserved: cpu=500m,memory=1Gi