apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: cpu-test-daemonset
  namespace: default
  labels:
    app: cpu-test
spec:
  selector:
    matchLabels:
      app: cpu-test
  template:
    metadata:
      labels:
        app: cpu-test
      annotations:
        weka.io/cores-ids: "1-3,4"
    spec:
      containers:
      - name: cpu-test
        image: busybox:1.35
        command:
        - sleep
        - "3600"
        resources:
          requests:
            cpu: "4"
            memory: "100Mi"
          limits:
            cpu: "4"
            memory: "100Mi"
      tolerations:
      - operator: Exists
      restartPolicy: Always